### ISSUE TITLE
defStyleAttr was ignored

### ISSUE THREAD

**Issue by hymanAndroid** [FabianTerhorst/FastLayout#11]
<img width="178" alt="2016-05-25 2 37 12" src="https://cloud.githubusercontent.com/assets/18735521/15530319/44141872-2286-11e6-8683-f903b2b15e92.png">

this is button ... the problem in class ActivityMainLayout's init method

```
 id_btn = new Button(getContext(), null, 0); //you generate code , you make defStyleAttr = 0 
```

**Comment by FabianTerhorst** [comment]
thanks for finding this bug. I released `0.0.2-alpha9` right now.
