### ISSUE TITLE
Provide exclude annotation

### ISSUE THREAD

**Issue by antoxa2584x** [FabianTerhorst/FastLayout#12]
You can add all but can not exclude some layouts.

**Comment by barisahmet** [comment]
You can use

> @Layouts(layouts = {"activity_main", "fragment_one"})

or

> @Layouts(ids = {R.layout.activity_main, R.layout.fragment_one})

**Comment by FabianTerhorst** [comment]
@barisahmet but he want something like `@Layouts(all = true, exclude = R.layout.sample_item)`.
I will add this later if i find some time.

**Comment by FabianTerhorst** [comment]
@antoxa2584x @barisahmet  i have added the exclude support in version 0.0.2-alpha11
