### ISSUE TITLE
LayoutCache generates only when @Layouts(all = true) 

### ISSUE THREAD

**Issue by antoxa2584x** [FabianTerhorst/FastLayout#14]
When I try to use annotation different to @Layouts(all = true), LayoutCache file not generates(

**Comment by FabianTerhorst** [comment]
@antoxa2584x can you show the annotation you are using when the cache does not get generated.

**Comment by antoxa2584x** [comment]
@FabianTerhorst I tried to use 
`@Layouts(all = true, exclude = {R.id.somelayout1,R.id.somelayout2})`
and
 `@Layouts(ids = {R.id.somelayout1,R.id.somelayout2})`

**Comment by FabianTerhorst** [comment]
@antoxa2584x is there any note, warning or error in the gradle messenger window?

**Comment by FabianTerhorst** [comment]
0.0.2-alpha21 has fixed some errors.
