### ISSUE TITLE
compatibility/gradle plugin 1.3.1

### ISSUE THREAD

**Issue by zetbrush** [FabianTerhorst/FastLayout#19]
So why plugin version at least 1.5.0 is needed? and how it can be integrated with 1.3.1 version

**Comment by FabianTerhorst** [comment]
The idea behind the 1.5 support was the transformer api, but this api isn´t needed right now. What is the problem for you not to update from 1.3.1 to 2.12?

**Comment by zetbrush** [comment]
currently I'm working on that but there is a lot of stuff to handle) for now, is there any way to integrate with 1.3.1? thanks.

**Comment by FabianTerhorst** [comment]
Im uploading version 0.0.2-alpha24 right now. This version doesn´t check for the gradle version.

**Comment by zetbrush** [comment]
Thanks a lot :) I hope this will reduce inflation latency dramatically)

**Comment by zetbrush** [comment]
@FabianTerhorst should I wait for release tag 0.0.2-alpha24?

**Comment by FabianTerhorst** [comment]
you can already use classpath 'io.fabianterhorst:fastlayout-gradle-plugin:0.0.1-alpha24'

**Comment by zetbrush** [comment]
ok, thanks.

**Comment by zetbrush** [comment]
@FabianTerhorst  So, I have declared my layouts like this

``````
 @Layouts(layouts = {"layout_bla",
        "layout_bla_bla"
})
public class AppLayouts {

    //@Layout("layout_bla");
    ILayout layoutBla;
} ```
I can't find LayoutCache or something...
so how I get the layout?


``````

**Comment by FabianTerhorst** [comment]
The fields are not needed anymore since it supports the R.java file. 

```
@Layouts(ids = {R.layout.activty_main}
)
public class AppLayouts {
}
```

**Comment by zetbrush** [comment]
I tried, in that case getting Attribute value must be constant syntax error

**Comment by FabianTerhorst** [comment]
When you got some errors in your layout file open a issue with the generated file and your layout xml. Some attributes aren´t supported right now.

**Comment by zetbrush** [comment]
the layout is simple as this, 

``` xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.RecyclerView xmlns:android="http://schemas.android.com/apk/res/android"
                                        android:id="@+id/vertical_recycler_explore"
                                        android:layout_width="match_parent"
                                        android:layout_height="match_parent">
</android.support.v7.widget.RecyclerView>
```

and getting AppLayouts.java:10: error: element value must be a constant expression

**Comment by FabianTerhorst** [comment]
The annotation processor is generating a file. This is stored inside your build folder build/generated/source/apt/dev/debug/.../..Layout.java. This file contains the whole error.

**Comment by zetbrush** [comment]
@FabianTerhorst  the reason was the library project, as one can't threat lib's R as constant value, anyway, I declared the layout, so how I'm getting the instance of that layout? :)

**Comment by FabianTerhorst** [comment]
The file with the @Layouts annotation needs to be in the same module like the layout files. Im generating  a object for every layout. For example activity_main is generating a object ActivityMainLayout. This can be used with new AcitivityMainLayout(context);

**Comment by zetbrush** [comment]
@FabianTerhorst Will something like this hack work? If yes what will be generated class name?

``` java
@Layouts(ids = {AppLayout.activity_main})
public class AppLayout {
    public static final int activity_main = R.layout.activity_main;

}
```

**Comment by FabianTerhorst** [comment]
When this is building without any error. There should be a object named ActivityMainLayout.

**Comment by FabianTerhorst** [comment]
but its doing the same like @Layouts(ids = {R.layout.activty_main}
)
public class AppLayouts {
}

**Comment by zetbrush** [comment]
that is invalid in library project, as R class declarations in library project are  `public static int`, and your annotation processor needs final's

**Comment by zetbrush** [comment]
also this warning is generated
warning: Unclosed files for the types '[dummy1465314602000]'; these types will not undergo annotation processing

**Comment by FabianTerhorst** [comment]
the R.java values are always public final, because there are constants. The warning is normal.

**Comment by zetbrush** [comment]
it's compile time error :) you can check it in library module example)

**Comment by FabianTerhorst** [comment]
Im using this in many apps. What android studio version are you using?

**Comment by FabianTerhorst** [comment]
The sample app is building for me.

**Comment by zetbrush** [comment]
I think you don't get me right, try declaring AppLayout in library module, and annotating layout resource from layout folder of that same library module, then you will get compile error like this 

``` java
AppLayout.java:8: error: element value must be a constant expression
@Layouts(ids = {R.layout.activity_main_2})
                        ^
1 error  
```

from main app module it works fine.

my studio version 2.1.1

**Comment by zetbrush** [comment]
the issue causing this is described here https://github.com/excilys/androidannotations/issues/78

**Comment by FabianTerhorst** [comment]
http://tools.android.com/tips/non-constant-fields

**Comment by FabianTerhorst** [comment]
On library projects @Layouts(layouts = {"activity_main"}) should work.

**Comment by FabianTerhorst** [comment]
its generating the ActivityMainLayout class

**Comment by FabianTerhorst** [comment]
the ids can´t work on library projects.

**Comment by zetbrush** [comment]
I was going to ask if string attributes will work ))) ok will try it

**Comment by zetbrush** [comment]
I can see it generated in build dir, but can't import it, any ideas why? strange)

**Comment by FabianTerhorst** [comment]
you have to look at the package name on top of the file

**Comment by FabianTerhorst** [comment]
its in the same location like your AppLayouts file.

**Comment by zetbrush** [comment]
exactly, but is invisible for usage

**Comment by FabianTerhorst** [comment]
have you tried to just add it into the code and press build. Even when its marked as an error.

**Comment by FabianTerhorst** [comment]
you can also try to clean and rebuild the project.

**Comment by zetbrush** [comment]
yeah, tried, compile error with cannot find symbol  (on generated class name)

**Comment by FabianTerhorst** [comment]
I have also tried it now in a Library project. And its working.

**Comment by zetbrush** [comment]
Yeah it should, as classes are generated properly, will have a close look on this, thanks for support!

**Comment by zetbrush** [comment]
ok, it worked, in sample app the issue was with clean project task, app's clean wasn't cleaning library project's build directory.

**Comment by zetbrush** [comment]
@FabianTerhorst is somehow resource directory hardcoded? as it keeps trying to lookup for layout in directory /src/main/res/layout/, but for example source set is modified with gradle config eg /res/layout/ ,so getting Error:/src/main/res/layout/main_activity.xml (No such file or directory)

**Comment by FabianTerhorst** [comment]
yes the directory is half hard coded. /src/main/res/layout/ is currently not dynamic.

**Comment by zetbrush** [comment]
I think it can be inited with static call via client, for custom res directory, and by simple check if not set, use the default :)

**Comment by FabianTerhorst** [comment]
i don´t think this is needed until the stable release, but im open for prs.
