### ISSUE TITLE
Various bugs

### ISSUE THREAD

**Issue by ivanfeli** [FabianTerhorst/FastLayout#2]
All these bugs were found with this layout: https://gist.github.com/drivfe/c8dcc6efb5dac448cbd5eebc9bcca85f

Version: 0.0.1-alpha13

To summarize:
1. Supports paddingLeft/Top/Bottom/Right but it does not work if you set just padding="10dp" which is supposed to do all four of them. Looks like .setPadding() must always take 4 params. 
2. Does not support "sp" for textSize
3. dp values does not work for layout_height and layout_width
4. toStartOf and toEndOf not supported (I think paddingStart/End neither)
5. Processor is not changing @+id/ to @id/ every time

**Comment by FabianTerhorst** [comment]
the 4. point should work when you use @id instead of @+id/, because it should only be used with @id. @+id/ is only for adding a new id.

**Comment by FabianTerhorst** [comment]
@drivfe is @+/id woking the same?

**Comment by FabianTerhorst** [comment]
alpha16 is supporting @+id/, because android is also support that

**Comment by FabianTerhorst** [comment]
alpha 17 is supporting the start and end
