### ISSUE TITLE
Benchmarks?

### ISSUE THREAD

**Issue by Kisty** [FabianTerhorst/FastLayout#22]
How fast is the layout compared to XML layout inflation? Can you do some benchmarks to show the improvements?

Thanks!

**Comment by ivanfeli** [comment]
https://cloud.githubusercontent.com/assets/5869863/14607128/f77fa9b4-0588-11e6-9fcc-4884ad6d709a.png

Source: https://nethergrim.github.io/performance/2016/04/16/anko.html

**Comment by Kisty** [comment]
It's not exactly what the library is but probably similar.

**Comment by FabianTerhorst** [comment]
The benchmark result should be the same.

**Comment by FabianTerhorst** [comment]
Maybe a little bit better, because im caching converted pixels from dps.
