### ISSUE TITLE
Some errors I found when I try use it in my project

### ISSUE THREAD

**Issue by barisahmet** [FabianTerhorst/FastLayout#6]
Thanks for this nice library! I really want to use it in my project. However I have few errors when I try to use it, since it's alpha version, it's okay I guess. Let me share issues with you:
- I can't use "0dip" anywhere.
- I can't use "dp" size in any text view (instead of "sp"), I know I should use "sp" but in some cases I need to use "dp", e.g. when I don't want text size change depended user settings in Android.

Regards.

**Comment by FabianTerhorst** [comment]
@barisahmet Is 0dip working when you replace 0dip with dp. Im not sure, but is dip the same like dp?

**Comment by barisahmet** [comment]
Yes, sorry about that. It was same, my bad.

**Comment by FabianTerhorst** [comment]
Im working currently on a way to support all different layout attributes. Im not sure if this will be possible, but it would be very nice.

**Comment by barisahmet** [comment]
Yes, this project needs support from community, the idea is amazing.

**Comment by FabianTerhorst** [comment]
To Init the object with the AttributeSet it's not possible, becuase it's a xml parserobject, so the pull Parser would parse it at runtime.

**Comment by FabianTerhorst** [comment]
But I add in the next Release Support for Dip, because when it's possible to declare it in the xml it should be supported. I will also take a look into the dp Support for textView for example.
